### ISSUE TITLE
Which version should I use?

### ISSUE THREAD

**Issue by tiagocabaco** [TasCL/ggdmc#2]
Hi, 

I am trying to figure out which version of this package should I should use: this repository's version or the open access version? Or are they the same? 

Thank you for the package! 

Best, 

Tiago

**Comment by yxlin** [comment]
Hi Tiago,

Thank you for being interested in ggdmc. The version currently hosted by the Comprehensive R Archive Network is 2.6.0 (correction, 0.2.6.0), which is the latest stable version. I recommend generally this version, because the user can install it directly via, for example, the installation interfere in RStudio, which would take care of the package dependency.  If you are interested in an older version, you can try the one archived here in TasCL github.  I have left the job there, so won't continue to maintain the repository here.  The one archived in my personal github, https://github.com/yxlin/ggdmc is the 2.6.1 (correction, 0.2.6.1), which is the latest developing version, which requires devtools and its supporting packages to install.

Best,

Yi-Shin Lin

**Comment by tiagocabaco** [comment]
Sorry, I completely missed your response. 

Thanks for letting me know about the different versions. All is clear now. 

Best, 
Tiago
